<?php
/**
 * This is an example how to calculate AUTHCODE for Paytrail E2 payment interface.
 * More information about AUTHCODE can be found in: https://docs.paytrail.com/payments/e2-interface/authcode/
 */


/**
 * @param array $paymentParameters
 * @return string
 */
function generateParamsIn(array $paymentParameters): string
{
    unset($paymentParameters["MERCHANT_HASH"]);
    return implode(",", array_keys($paymentParameters));
}

/**
 * @param $paymentParameters
 * @return string
 */
function generateAuthcode($paymentParameters): string
{
    $authcodeString = implode("|", array_values($paymentParameters));
    return strtoupper(hash("sha256", $authcodeString));
}

/**
 * Formats array of item rows to form
 * [
 *      "ITEM_TITLE[0]" => "test title",
 *      "ITEM_TITLE[1]" => "test title 2"
 * ]
 *
 * @param array $itemRows
 * @return array
 */
function formatItemRows(array $itemRows): array
{
    $items = [];

    foreach ($itemRows as $title => $item) {
        foreach ($item as $index => $value) {
            $items["{$title}[$index]"] = $value;
        }
    }

    return $items;
}

/**
 * Prints submittable HTML with submit button to test the authcode and payment
 *
 * @param $paymentParameters
 */
function formatHtml($paymentParameters): void
{
    array_walk($paymentParameters, static function ($value, $key) use (&$inputs) {
        $inputs .= "<input name=\"$key\" type=\"hidden\" value=\"$value\">\n";
    });

    echo <<<END
HTML form for testing
-----------------------
<form action="https://payment.paytrail.com/e2" method="post">
$inputs
<input type="submit" value="Pay here">
</form>
END;
}

$merchantId = 13466;
$merchantHash = "6pKF4jkv97zmqBJ3ZL8gUw5DfT2NMQ";
$amount = 59;
$paymentMethods = "1,2";


// See accepted parameters from https://docs.paytrail.com/payments/e2-interface/validation/
$paymentParameters = [
    'MERCHANT_HASH' => $merchantHash,
    'MERCHANT_ID' => $merchantId,
    'URL_SUCCESS' => 'https://test.url.com/success',
    'URL_CANCEL' => 'https://test.url.com/cancel',
    'ORDER_NUMBER' => 'PHP-EXAMPLE-ORDER-' . random_int(0, 1000),
    'PARAMS_IN' => '', //Will be auto generated by the script
    'PARAMS_OUT' => 'PAYMENT_ID,TIMESTAMP,STATUS',
    'AMOUNT' => $amount, //Item rows and AMOUNT shouldn't be provided at the same time, remove this to submit item rows
    'PAYMENT_METHODS' => $paymentMethods,
    'MSG_UI_MERCHANT_PANEL' => 'Message',
    'URL_NOTIFY' => 'https://test.url.com/notify',
    'LOCALE' => 'fi_FI',
    'CURRENCY' => 'EUR',
    'REFERENCE_NUMBER' => '1205769750',
    'PAYER_PERSON_PHONE' => '040123123',
    'PAYER_PERSON_EMAIL' => 'theodor.tester@testcompany.com',
    'PAYER_PERSON_FIRSTNAME' => 'Theodor',
    'PAYER_PERSON_LASTNAME' => 'Tester',
    'PAYER_COMPANY_NAME' => 'Testcompany',
    'PAYER_PERSON_ADDR_STREET' => 'Test street',
    'PAYER_PERSON_ADDR_POSTAL_CODE' => '23131',
    'PAYER_PERSON_ADDR_TOWN' => 'Test town',
    'PAYER_PERSON_ADDR_COUNTRY' => 'Test country',
    'VAT_IS_INCLUDED' => '0',
    'ALG' => '1',
];

$itemRows = [
    'ITEM_TITLE' =>
        [
            'Rubber boot',
            'Basket ball',
        ],
    'ITEM_ID' =>
        [
            '100',
            '101',
        ],
    'ITEM_QUANTITY' =>
        [
            '2',
            '1',
        ],
    'ITEM_UNIT_PRICE' =>
        [
            '10',
            '5',
        ],
    'ITEM_VAT_PERCENT' =>
        [
            '24',
            '24',
        ],
    'ITEM_DISCOUNT_PERCENT' =>
        [
            '0',
            '0',
        ],
    'ITEM_TYPE' =>
        [
            '1',
            '1',
        ],
];

// Discards item rows and VAT_IS_INCLUDED if AMOUNT is present in payment parameters
if (isset($paymentParameters["AMOUNT"])) {
    $itemRows = [];
    unset($paymentParameters['VAT_IS_INCLUDED']);
}

$itemRows = formatItemRows($itemRows);
$paymentParameters = array_merge($paymentParameters, $itemRows);

$paymentParameters["PARAMS_IN"] = generateParamsIn($paymentParameters);
$paymentParameters["AUTHCODE"] = generateAuthcode($paymentParameters);
formatHtml($paymentParameters);
